### PR TITLE
Sdp dual cut with SVEC

### PR DESCRIPTION
**Pull request by chriscoey**

### CODE REVIEW

**Comment by emreyamangil** [comment]
I am waiting on this to see if we can add an example before merging that was returning a wrong value and got corrected with this PR, thanks!

**Comment by mlubin** [comment]
Note that we don't have any SDP solvers running on appveyor or travis-CI, so the build statuses don't mean much for SDP changes.

**Comment by emreyamangil** [comment]
Yea I tried it on my end, with this update & Mosek the unit test is passing, though I would want to see an example where it indeed fixes something, right?

**Comment by mlubin** [comment]
Yep

**Pull request closed without merging**
