### PR TITLE
changed some option names for consistency, removed the slacks

### PR DESCRIPTION
**Pull request by chriscoey**
Much less cluttered without detecting slacks, which only affected the MIP and hence was not worthwhile assuming good MIP solver. Also makes all the mathy code much easier to read.

### CODE REVIEW

**Comment by mlubin** [comment]
If these are meant to be the final names, could you update the README at least for the public options?

**Comment by chriscoey** [comment]
will do

**Comment by chriscoey** [comment]
some checks failed due to irrelevant reasons

**Comment by mlubin** [comment]
the mumps server is very frequently down

**Comment by ccoffrin** [comment]
Ya!  Why is that?  I want a mirror!

**Comment by mlubin** [comment]
so make one and we'll switch to it :)

**Comment by ccoffrin** [comment]
touche

**Pull request merged**
