### PR TITLE
Store cone data separately for different cone types, improve clarity of cut adding functions

### PR DESCRIPTION
**Pull request by chriscoey**
this isn't quite ready to go yet, a few more things to clean up

### CODE REVIEW

**Comment by chriscoey** [comment]
OK I'll merge this when it passes. I still want to rewrite some small parts of the SDP cuts section (do them in smat, not svec space).

And we should figure out what to do when we have repeat integer sols in MIP-solver driven (or even in iterative too maybe). Repeat integer sols happen extremely often it seems. eg see this cblib misocp problem output from mip_solver_drives and defaults:

```
Finished MIP-solver-driven outer approximation algorithm:
 - Total time (s)       =       1.07e+01
 - Status               =        Optimal
 - Best feasible obj.   =  +2.878104e+05
 - Final OA obj. bound  =  +2.878104e+05
 - Relative opt. gap    =      0.000e+00
 - Conic iter. count    =           2229
 - Feas. solution count =           2216
 - Integer repeat count =           2210

Timers (s):
 - Setup                =       1.97e+00
 -- Transform data      =       1.48e-04
 -- Create conic data   =       5.72e-03
 -- Create MIP data     =       1.46e-01
 -- Load/solve relax    =       1.46e+00
 -- Add relax cuts      =       2.94e-01
 - MIP-driven algorithm =       8.77e+00
 -- Calculate conic b   =       1.91e-02
 -- Load conic data     =       1.74e+00
 -- Solve conic         =       2.51e+00
 -- Add conic cuts      =       4.59e-01
 -- Add conic solution  =       2.05e-01
 -- Calc. outer inf.    =       8.01e-03
 -- Use heur. callback  =       2.81e-01
```

There were only about 20 unique integer sols out of over 2000. And we spend about the same amount of time setting up and solving conic problems and adding (redundant) cuts as we do solving the MIP.

**Comment by chriscoey** [comment]
I think tests failed because of `@variable(model_mip)`. I am on JuMP master.

**Comment by mlubin** [comment]
Well, don't be on JuMP master

**Comment by mlubin** [comment]
Have you tested this on various problems to check for performance regressions?

**Comment by chriscoey** [comment]
OK I'm a lot happier with how cuts are done in this version. I'll merge this and then look at primal cuts.

**Comment by chriscoey** [comment]
checking for performance regressions on some cblib problems

**Pull request merged**
