### PR TITLE
Remove reference to ``MathProgBase.defaultConicSolver`` inside conic algorithm

### PR DESCRIPTION
**Pull request by joehuchette**
Remove check in conic algorithm between continuous solver and MathProgBase default conic solver

### CODE REVIEW

**Comment by mlubin** [comment]
Looks good but as is this will break things and I assume fail tests on MPB 0.5. We need a full fix.

**Comment by joehuchette** [comment]
I'm not sure why this would break things on MPB. Fully excising the default solvers will, though, and I'm not sure how you want to approach that.

**Comment by mlubin** [comment]
```julia
m = Model(solver=PajaritoSolver())
@variable(m, x, Bin)
@constraint(m, norm([x]) <= 0)
solve(m)
```
gives
```
ERROR: MethodError: no method matching supportedcones(::MathProgBase.DefaultConicSolver)
Closest candidates are:
  supportedcones(::Pajarito.ConicDualWrapper) at /home/mlubin/.julia/v0.5/Pajarito/src/conic_dual_solver.jl:54
  supportedcones(::ConicNonlinearBridge.ConicNLPWrapper) at /home/mlubin/.julia/v0.5/ConicNonlinearBridge/src/nonlinear_to_conic.jl:221
  supportedcones(::Int64) at /home/mlubin/.julia/v0.5/MathProgBase/src/SolverInterface/SolverInterface.jl:27
  ...
 in loadproblem!(::Pajarito.PajaritoConicModel, ::Array{Float64,1}, ::SparseMatrixCSC{Float64,Int64}, ::Array{Float64,1}, ::Array{Any,1}, ::Array{Any,1}) at /home/mlubin/.julia/v0.5/Pajarito/src/conic_algorithm.jl:260
 in #build#114(::Bool, ::Bool, ::JuMP.ProblemTraits, ::Function, ::JuMP.Model) at /home/mlubin/.julia/v0.5/JuMP/src/solvers.jl:424
 in (::JuMP.#kw##build)(::Array{Any,1}, ::JuMP.#build, ::JuMP.Model) at ./<missing>:0
 in #solve#109(::Bool, ::Bool, ::Bool, ::Array{Any,1}, ::Function, ::JuMP.Model) at /home/mlubin/.julia/v0.5/JuMP/src/solvers.jl:219
 in solve(::JuMP.Model) at /home/mlubin/.julia/v0.5/JuMP/src/solvers.jl:201
```
which is not a good failure mode.

It also fails the unit tests because we test with default solvers.

**Comment by joehuchette** [comment]
I'm seeing an even earlier failure at
```jl
julia> m = Model(solver=PajaritoSolver())
ERROR: UndefVarError: defaultMIPsolver not defined
 in Pajarito.PajaritoSolver() at /Users/huchette/.julia/v0.5/Pajarito/src/solver.jl:102
```
but agreed that it's not a good failure mode.

**Comment by mlubin** [comment]
My example was running on MPB 0.5.

**Comment by chriscoey** [comment]
removed all other references also in #240

**Pull request closed without merging**
