### PR TITLE
Initial performance profiling tools

### PR DESCRIPTION
**Pull request by emreyamangil**
This PR adds an initial performance profiling option.

### CODE REVIEW

**Comment by mlubin** [comment]
Oops, we have merge conflicts now

**Comment by emreyamangil** [comment]
Time for exercise!! :)

**Comment by emreyamangil** [comment]
YES!

**Comment by mlubin** [comment]
Tests failing:
```
Infeasible NLP problem
ERROR: LoadError: type PajaritoSolver has no field cut_switch
```

**Pull request merged**
