### PR TITLE
give MIP solver remaining time before timeout, fix Pajarito return status

### PR DESCRIPTION
**Pull request by chriscoey**
Pajarito now gives the MIP solver a timeout in the iterative algorithm. Also, we now catch the return status of the MIP solver properly, and return an appropriate Pajarito status.

### CODE REVIEW

**Comment by mlubin** [comment]
Tested locally?

**Comment by mlubin** [comment]
It would be nice to have this covered by unit tests.

**Comment by chriscoey** [comment]
I can test that it returns `:UserLimit` if I can give it a large enough instance in the tests and, say, 5 seconds total timeout value. But I need that sufficiently large instance.

**Comment by chriscoey** [comment]
and yes i tested it on the pp-n100-d10000.cbf file and it worked

**Comment by mlubin** [comment]
You could dump one of the cbf instances in MPB format to a JLD file and read it back during the tests (as long as the JLD file isn't too big)

**Pull request merged**
