### PR TITLE
add subopt solver tests, print log_level 3 on some tests

### PR DESCRIPTION
**Pull request by chriscoey**
this means runtests has more output for half a dozen problems. but it will significantly improve code coverage

### CODE REVIEW

**Comment by mlubin** [comment]
You could do the redirect_stdout trick to keep the tests quiet.

**Comment by chriscoey** [comment]
does it really matter? and where would i do that, right where I call solve?

**Comment by mlubin** [comment]
No, it doesn't really matter, but you could do it around the solve call.

**Comment by chriscoey** [comment]
We can do it if someone complains. We get a ton of warnings from MOSEK and GLPK on the Pajarito-as-MISOCP-solver tests anyway. So either everything should be quieted, or nothing at all.

**Pull request merged**
