### PR TITLE
A-opt is back

### PR DESCRIPTION
**Pull request by mlubin**
Let's see if travis approves

### CODE REVIEW

**Comment by mlubin** [comment]
It does not. But locally things seem to work if I bump ``eps`` to ``1e-7`` in SCS.

**Comment by chriscoey** [comment]
hm. did it work with mosek for you?

**Comment by mlubin** [comment]
For ``mip_solver = Pajarito(GLPK,ECOS)``, I get optimal for ``cont_solver = Mosek`` and ``cont_solver = SCS(1e-7)``, failure for ``SCS(1e-6)``.

**Comment by chriscoey** [comment]
do you get lots of warnings? glpk numerical instability? mosek warnings?

**Comment by mlubin** [comment]
GLPK warnings but still converges. Don't see anything from mosek

**Pull request closed without merging**
