### PR TITLE
objval inf fix

### LINKED ISSUE #72: a case where printing be ugly
The "Inf"s messed up the spacing
Also, possible to give warnings above the table?

```
Iteration   MIP Objective     NLP Objective   Optimality Gap   Best Solution    Primal Inf.      OA Inf.
WARNING: Solver does not appear to support adding constraints to an existing model. Hot-start is disabled.
        0   +1.7873225e+00   -Inf   +Inf   +Inf   +3.4565384e-01   +3.4488514e-01
```

### PR DESCRIPTION
**Pull request by emreyamangil**
This PR updates the objective values to max 1e+75.

Closes #72

### CODE REVIEW

**Comment by emreyamangil** [comment]
Hmmm appveyor started to crash inside Cbc for some reason, confusion!

**Comment by mlubin** [comment]
I don't really like using ``1e+75`` instead of ``Inf``, why not just print ``Inf`` better?

**Comment by emreyamangil** [comment]
I see, let me give that a quick try

**Comment by emreyamangil** [comment]
This doesn't look good, I will write a print function, something like CPLEX, if its infeasible, we don't print anything but keep the alignment instead of 1e+75 printing, will finish this today!

**Comment by emreyamangil** [comment]
This looks better, if the prints are inf, this turns them into spaces of equivalent length!

**Pull request merged**
