### PR TITLE
transition to cbf for conic tests

### LINKED ISSUE #317: put tests into cbf form, add more rsoc tests from library

### PR DESCRIPTION
**Pull request by chriscoey**
fixes #317 
clean up tests and remove convex.jl dependency

### CODE REVIEW

**Comment by chriscoey** [comment]
issue now is that for two of the new cbf tests (old problems -Optimal SOCRot, and Zero cones), the solution is permuted from what it should be given the initial model. these tests were fine before moving to cbf. so maybe cbf is permuting the indices of variables?

**Comment by chriscoey** [comment]
OK I've put the SOC tests in CBF. Still need to add more small nontrivial problems from cblib, especially with rotated soc. 

Then I'll do exp tests, and add some easy ones from cblib.

Then SDP tests. Will put A,D,E opt problems in CBF. But probably want maybe a polynomial problem or a couple of faster SCIP SDP benchmark instances if any are fast.

**Comment by chriscoey** [comment]
If we identify issues with conicbenchmarkutilities this way, then we should fix those and then release CBU, because I use a jump to cbf function that is only on master.

**Comment by mlubin** [comment]
> so maybe cbf is permuting the indices of variables?

There are two things going on:
1. We don't have a way to map between Convex.jl variables and variables in the cbf file. I wouldn't recommend trying to do that.
2. The cbf exponential cone is defined in a different order from the MPB exponential cone, so we perform a permutation for Exp variable cones. This doesn't affect convex.jl models because convex.jl doesn't use variable cones.

The best thing to do at the moment is to take the solution vector and give it to a function that processes the total infeasibilities from the CBF model, like [here](https://github.com/mlubin/PajaritoSupplement/blob/4d4c4fa4f3fc3cf353dc2f31b7f728eb503cadd1/scripts/process.jl#L25) and test for small violations in a generic way.

**Comment by chriscoey** [comment]
some tests fail on MSD, but too bad

**Comment by chriscoey** [comment]
also Gurobi fails on a few tests where no other solvers fail

**Comment by chriscoey** [comment]
lots of CPLEX MSD errors, eg Hijazi problem coming back optimal. Seems that the incumbent callback is pretty important if you want to use MSD with CPLEX

**Comment by chriscoey** [comment]
OK problem now is in the pajarito-in-pajarito MISOCP OA tests, on the first one, there is an immediate failure because JuMP seems to be making a LinearQuadratic model instead of a conic one. @mlubin 

```
Starting iterative outer approximation algorithm
ExpSOC SOC in MIP: Error During Test
  Got an exception of type ErrorException outside of a @test
  Continuous solver specified is not a nonlinear solver recognized by MathProgBase
  
   in NonlinearModel(::Pajarito.PajaritoSolver) at /home/coey/.julia/v0.5/Pajarito/src/solver.jl:157
   in LinearQuadraticModel(::Pajarito.PajaritoSolver) at /home/coey/.julia/v0.5/Pajarito/src/solver.jl:173
   in #build#114(::Bool, ::Bool, ::JuMP.ProblemTraits, ::Function, ::JuMP.Model) at /home/coey/.julia/v0.5/JuMP/src/solvers.jl:405
   in (::JuMP.#kw##build)(::Array{Any,1}, ::JuMP.#build, ::JuMP.Model) at ./<missing>:0
   in #solve#109(::Bool, ::Bool, ::Bool, ::Array{Any,1}, ::Function, ::JuMP.Model) at /home/coey/.julia/v0.5/JuMP/src/solvers.jl:166
   in (::JuMP.#kw##solve)(::Array{Any,1}, ::JuMP.#solve, ::JuMP.Model) at ./<missing>:0
   in solve_iterative!(::Pajarito.PajaritoConicModel) at /home/coey/.julia/v0.5/Pajarito/src/conic_algorithm.jl:1330

```

**Comment by mlubin** [comment]
It's probably because the sub-model has no SOC constraints added when you call ``solve()``.

**Comment by chriscoey** [comment]
OK, so how do I tell it that this is supposed to be a conic model, before any SOC cuts get added?

**Comment by mlubin** [comment]
You can't at the moment besides adding a dummy SOC constraint. I'd skip this test and open a JuMP issue.

**Comment by chriscoey** [comment]
@mlubin do you know where this 0.6 dep warning comes from 
`WARNING: deprecated syntax "_ as an rvalue".
`

**Comment by chriscoey** [comment]
iterative tests are passing for me (except on Gurobi, a couple of weird failures), but lots of MSD tests fail with CPLEX and Gurobi

**Comment by mlubin** [comment]
> do you know where this 0.6 dep warning comes from

Don't name variables ``_``.

It would be nice to understand why MSD is failing. Did the tests used to pass?

**Comment by chriscoey** [comment]
The msd tests used to pass on glpk only

**Comment by chriscoey** [comment]
i've re-enabled GLPK MSD because it was only one minor unimportant test that it failed on

**Comment by chriscoey** [comment]
i added in cbc solver, but it fails on dozens of tests. quite unreliable.

**Comment by chriscoey** [comment]
tests pass, including MSD with glpk 
💯

**Pull request merged**
